---
title: "R Notebook"
output: github_document
---

```{r}
library(dada2) 
```
```{r}
install.packages("Rcpp")
```



```{r}
library(dada2)
packageVersion("dada2")
```

```{r}
install.packages("Rcpp")
```



```{r}
path <- "/home/rstudio/essai-dada2/MiSeq_SOP" # Cela attribue à la variable path le chemin du dossier MiSeq_SOP qui se trouve dans home rstudio.
list.files(path) # Cette fonction affiche la liste des fichiers dans le répertoire spécifié par path.
```

```{r}
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))# création d' une variable fnFs contenant la liste triée de tous les fichiers fastq pour les lectures avant, présents dans le répertoire spécifié, en utilisant les noms qui contiennent _R1_001.fastq.

fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE)) # création d' une variable fnRs contenant la liste triée de tous les fichiers fastq pour les lectures reverse, présents dans le répertoire spécifié, en utilisant les noms qui contiennent _R2_001.fastq.
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)  # Elle divise chaque nom de fichier en parties basées sur les _, et elle garde uniquement la première partie (le nom de l'échantillon) avant le premier _. 

```


```{r}
library(dada2)
```
```{r}
install.packages("Rcpp")
```

```{r}
library(dada2)
```
```{r}
install.packages("Rcpp")
```


```{r}
library(dada2)
```


```{r}
plotQualityProfile(fnFs[1:2]) # Tracer le profil de qualité des fichiers fastq fnFs pour les deux premiers fichiers. le score de qualité permet d'indiquer la fiabilité d'une base dans les données de sequencage, plus le score est elevé plus cette base est fiable.l'interpretation du graphe:on observe que le score de qualité est plus élevé au  début de lecture (bases au début), et il diminue à la fin de la lecture(dernières bases) , cela peut indiquer qu'il y a de la perte de qualité, ainsi une coupe des lectures peut être nécessaire pour éliminer ces mauvaises sections.
```

```{r}
plotQualityProfile(fnRs[1:2]) # Tracer le profil de qualité des fichiers fastq fnRs pour les deux premiers fichiers. le score de qualité permet d'indiquer la fiabilité d'une base dans les données de sequencage, plus le score est elevé plus cette base est fiable.l'interpretation du graphe:on observe que le score de qualité est plus élevé au  début de lecture (bases au début), et il diminue à la fin de la lecture(dernières bases) , cela peut indiquer qu'il y a de la perte de qualité, ainsi une coupe des lectures peut être nécessaire pour éliminer ces mauvaises sections.
```
```{r}
# Place filtered files in filtered/ subdirectory
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))# création d'un vecteur filtFs contenant les chemins d'accès complets vers les fichiers filtrés des séquences Fs, en les enregistrant dans le répertoire "filtered" sous un nom de fichier correspondant à chaque échantillon.
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))#création d'un vecteur filtFs contenant les chemins d'accès complets vers les fichiers filtrés des séquences Rs, en les enregistrant dans le répertoire "filtered" sous un nom de fichier correspondant à chaque échantillon.
names(filtFs) <- sample.names# Chaque fichier dans filtFs sera étiqueté avec un nom d'échantillon contenant dans sample.names.
names(filtRs) <- sample.names # Chaque fichier dans filtRs sera étiqueté avec un nom déchantillon contenant dans sample.names.
```


```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
head(out) # Cette ligne de code exécute le filtrage et le nettoyage des séquences FASTQ pour plusieurs échantillons, en utilisant des paramètres tels que la longueur de coupe(Les séquences sont coupées à 240 bases pour les séquences forward (fnFs) et à 160 bases pour les séquences reverse (fnRs)), le seuil d'erreur maximal maxEE=(2,2) (Les séquences avec un nombre d'erreurs cumulées supérieur à 2 seront éliminées), maxN=0 (Si une séquence contient une base N, elle sera rejetée) truncQ=2 (Les bases ayant un score de qualité inférieur à 2 (Phred < 2) seront coupées ou supprimées) rm.phix= true (retirer les sequences de phix), compress=True(les fichiers filtrés seront compressés au format gzip).La variable out contient le résultat de la fonction filterAndTrim(), data.frame qui contient des informations sur le nombre de séquences avant et après le filtrage.
```
```{r}
errF <- learnErrors(filtFs, multithread=TRUE)# learnErrors() dans DADA2 apprend un modèle d'erreur pour les séquences forward  afin de corriger les erreurs de séquençage. Elle utilise les séquences filtrées (contenues dans filtFs) pour estimer les erreurs de séquençage typiques (substitutions, insertions, etc.).errF : L'objet contenant le modèle d'erreur appris pour les séquences forward. 
```
```{r}
errR <- learnErrors(filtRs, multithread=TRUE)# apprend un modèle d'erreur pour les séquences reverse pour corriger les erreurs.
```

```{r}
plotErrors(errF, nominalQ=TRUE)# génère un graphique qui montre les erreurs de séquençage apprises dans les séquences forward (errF). Le graphique aide à visualiser le taux d'erreur en fonction des scores de qualité (Phred), et à évaluer la qualité globale de vos données de séquençage, nominalQ= TRUE Cela signifie que les scores de qualité (Q-scores) sur l'axe des ordonnées du graphique seront affichés avec les valeurs nominales, c'est-à-dire les valeurs en Phred.
```

```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)# la fonction dada  prend les séquences filtrées forward  et le modèle d'erreur estimé, et utilise une approche basée sur le maximum de vraisemblance pour identifier les variantes exactes de séquences (appelées ASVs pour "Amplicon Sequence Variants") les résultats indiquent que sample 1: on a 7113 reads(fragments d'adn sequencés apres le filtrage) et dans ces 7113 seq on a 1979 sequences uniques 
```

```{r}
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)#la fonction dada  prend les séquences filtrées reverse   et le modèle d'erreur estimé, et utilise une approche basée sur le maximum de vraisemblance pour identifier les variantes exactes de séquences (appelées ASVs pour "Amplicon Sequence Variants")
```
```{r}
dadaFs[[1]]# Elle va nous montrer les ASVs et leurs abondances dans le premier échantillon.
```

```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample  cette fonction te permet de fusionner les lectures forward et reverse pour obtenir des séquences plus complètes
head(mergers[[1]])# permet de  montrer un aperçu des premières séquences fusionnées pour le premier échantillon dans l'objet mergers
```
```{r}
seqtab <- makeSequenceTable(mergers)# Cette commande crée une table de séquences à partir des résultats de la fusion des lectures paired-end, où chaque ASV est représentée par une colonne et l'abondance dans chaque échantillon par une ligne. Elle te permet d'obtenir un résumé complet des ASVs détectées et de leur abondance dans tes échantillons.
dim(seqtab) #dim(seqtab) renvoie un vecteur contenant les dimensions de la table de séquences (le nombre d'échantillons et d'ASVs). l'interpretation du résultat : Il y a 20 échantillons dans la table de séquences (chaque échantillon correspond à une ligne dans la table). 293 : Il y a 293 ASVs (Amplicon Sequence Variants) détectées dans les échantillons (chaque ASV correspond à une colonne dans la table).
```
```{r}
table(nchar(getSequences(seqtab))) #Extrait toutes les séquences (ASVs) de la table de séquences. nchar() : Calcule la longueur de chaque ASV. table() : Compte combien d'ASVs ont une longueur donnée. l'interpretation des résultats: 88 ASV ont une longueur de 252 bases
```

```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)#Supprime les séquences chimériques de la table seqtab.
dim(seqtab.nochim)#Renvoie les dimensions de la table après élimination des chimères, te montrant combien d'échantillons et d'ASVs restent après cette étape de nettoyage.l'interpretation des résultats: il reste 20 échantillons, 61 chiméres ont été identifiés il reste ainsi 232 ASV
```
```{r}
sum(seqtab.nochim)/sum(seqtab)# elle permet de calculer la proportion de séquences non chimériques après suppression des chimères, par rapport à l'ensemble des séquences initiales. l'interprétation des résultats  signifie que 96.4% des séquences dans ta table initiale (avant la suppression des chimères) étaient non chimériques et ont été conservées dans la table seqtab.nochim après l'élimination des chimères.
```
```{r}
getN <- function(x) sum(getUniques(x))# getN est une fonction définie pour calculer la somme des séquences uniques dans un objet DADA2.getUniques(x) extrait les séquences uniques de l'objet x.sum(getUniques(x)) additionne ces séquences uniques pour obtenir une somme totale ou abondance.
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))#crée une table nommée track avec les colonnes suivantes :out : Nombre de séquences après filterAndTrim().sapply(dadaFs, getN) : Nombre de séquences uniques après dénucléotidation des lectures forward. sapply(dadaRs, getN) : Nombre de séquences uniques après dénucléotidation des lectures reverse.sapply(mergers, getN) : Nombre de séquences uniques après fusion des lectures forward et reverse.rowSums(seqtab.nochim) : Nombre total d'ASVs non chimériques après élimination des chimères.
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)#colnames(track) attribue des noms de colonnes explicites à la table track pour clarifier les différentes étapes du traitement.rownames(track) associe chaque ligne de la table à un échantillon spécifique, basé sur sample.names.head(track) affiche les premières lignes de la table pour que tu puisses vérifier les données et voir comment les séquences évoluent à travers chaque étape du pipeline DADA2.
```
```{r}
taxa <- assignTaxonomy(seqtab.nochim, "/home/rstudio/essai-dada2/silva_nr_v132_train_set.fa.gz?download=1", multithread=TRUE)#la commande assignTaxonomy() affecte des classifications taxonomiques aux séquences uniques ou ASVs présentes dans seqtab.nochim, en utilisant une base de données de séquences  SILVA.Elle attribue des groupes taxonomiques aux ASVs à partir du phylum jusqu'à l'espèce, et le résultat est stocké dans taxa, un data frame contenant la classification de chaque ASV.


```

```{r}
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)#taxa.print <- taxa : Crée une copie de taxa.rownames(taxa.print) <- NULL : Supprime les noms de séquences (ASVs) dans taxa.print.head(taxa.print) : Affiche les premières lignes de la table sans les noms de séquences, montrant uniquement les informations taxonomiques.Cette procédure permet de simplifier l'affichage de la table pour se concentrer sur les données taxonomiques, rendant le tableau plus lisible et facile à interpréter.
```

```{r}
unqs.mock <- seqtab.nochim["Mock",]
unqs.mock <- sort(unqs.mock[unqs.mock>0], decreasing=TRUE) # Drop ASVs absent in the Mock
cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")#Ce code permet d'extraire, filtrer et trier les séquences uniques détectées dans un échantillon Mock, puis affiche combien d'ASVs ont été identifiées dans cet échantillon de contrôle.

```

```{r}
mock.ref <- getSequences(file.path(path, "HMP_MOCK.v35.fasta"))
match.ref <- sum(sapply(names(unqs.mock), function(x) any(grepl(x, mock.ref))))
cat("Of those,", sum(match.ref), "were exact matches to the expected reference sequences.\n")#le fichier HMP_MOCK.v35.fasta est lu et stocké dans mock.ref.Vérification des correspondances : Pour chaque ASV détectée dans l'échantillon Mock, on vérifie si son nom apparaît dans les séquences de référence mock.ref. Si oui, cette ASV est considérée comme une correspondance.Affichage du résultat : Le nombre d'ASVs qui correspondent exactement aux séquences de référence est affiché avec un message.
```


```{r}
library(phyloseq)
```
```{r}
packageVersion("phyloseq")
```
```{r}
packageVersion("phyloseq")

```


```{r}
library(Biostrings)
```
```{r}
packageVersion("Biostrings")
```
```{r}
library(ggplot2)

```
```{r}
packageVersion("ggplot2")
```
```{r}
theme_set(theme_bw())#configure ggplot2 pour que tous les graphiques générés après cette commande aient un fond blanc avec des axes noirs, offrant un style visuel noir et blanc
```
```{r}
samples.out <- rownames(seqtab.nochim)#extrait les noms des échantillons de la table des séquences non chimériques seqtab.nochim et les stocke dans la variable samples.out.
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)#permet de diviser les noms d'échantillons en utilisant "D" comme séparateur et d'extraire la partie avant le "D". Le résultat est stocké dans la variable subject.
gender <- substr(subject,1,1)#extrait le premier caractère de chaque élément dans la variable subject et le stocke dans la variable gender
subject <- substr(subject,2,999)#permet d'exclure le premier caractère de chaque élément dans la variable subject, en gardant uniquement le reste de la chaîne, à partir du deuxième caractère jusqu'à la fin.
day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
samdf$When <- "Early"
samdf$When[samdf$Day>100] <- "Late"
rownames(samdf) <- samples.out #  Extrait les numéros de jour des noms d'échantillons (extrait la partie après "D" et la convertit en entier).Crée un data frame samdf avec les colonnes : Subject, Gender, et Day.Ajoute une colonne When, initialisée à "Early".Modifie la colonne When à "Late" pour les lignes où Day est supérieur à 100.Définit les noms des lignes du data frame samdf en fonction des noms des échantillons dans samples.out. en résumé ce code permet de créer un tableau d'échantillons avec des informations sur le sujet, le genre, le jour, et la phase (early ou late ) de l'échantillon en fonction du jour de prélèvement.
```

```{r}
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))#crée un objet phyloseq en combinant trois types de données :Table des séquences (ASV) (seqtab.nochim), avec les séquences non chimériques.Métadonnées des échantillons (samdf), contenant des informations sur les échantillons (comme le genre, le jour, la phase).Table de taxonomie (taxa), contenant la classification taxonomique des séquences (ASV).
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample

```
```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps 
#crée un objet DNAStringSet à partir des noms de séquences (ASV) dans l'objet phyloseq (ps), dna <- Biostrings::DNAStringSet(taxa_names(ps)) : Récupère les noms des séquences (ASV) et les convertit en une structure de données DNAStringSet, names(dna) <- taxa_names(ps) : Associe les noms des séquences à l'objet dna.Ajoute cet objet dna à l'objet phyloseq (ps) en tant que données supplémentaires :ps <- merge_phyloseq(ps, dna) : Fusionne les informations de séquences (dna) avec l'objet phyloseq existant.Renomme les noms taxonomiques des ASV pour les formater comme "ASV1", "ASV2", etc. :taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps))) : Renomme les ASV dans l'objet phyloseq avec un format numérique séquentiel (ASV1, ASV2, etc.).
```

```{r}
plot_richness(ps, x="Day", measures=c("Shannon", "Simpson"), color="When")#Cette commande produit un graphique de diversité alpha (richesse des communautés) en utilisant les indices de diversité Shannon et Simpson, avec les échantillons regroupés par "Day" et colorés par "When" pour montrer la variation de la diversité entre les différentes phases (Early et Late). Ce type de graphique permet d'explorer comment la diversité change au fil du temps et entre les groupes de traitements.
```


```{r}
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")#Normalisation des comptes : Il transforme les comptes d'OTU/ASV dans chaque échantillon en proportions relatives, afin de comparer les abondances des taxons entre les échantillons de manière proportionnelle, plutôt qu'absolue.Analyse NMDS : Il effectue une ordination NMDS basée sur la distance de Bray-Curtis, afin de visualiser les relations de similarité ou de dissimilarité entre les échantillons en réduisant la dimensionnalité des données.
```



```{r}
plot_ordination(ps.prop, ord.nmds.bray, color="When", title="Bray NMDS")# Cette commande génère un graphique NMDS pour visualiser les similarités entre les échantillons, en coloriant les échantillons selon la variable "When". Cela permet de voir si les échantillons des phases Early et Late se regroupent ou se séparent dans l'espace ordonné.
```
```{r}
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, x="Day", fill="Family") + facet_wrap(~When, scales="free_x")# Ce code sélectionne les 20 ASVs les plus abondants, les normalise en proportions relatives, et génère un barplot des familles taxonomiques, séparé par les périodes "Early" et "Late"
```